/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.oltecnologias.hype.gui;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class GerarRelatorioDialog extends java.awt.Dialog {

    /**
     * Creates new form GerarRelatorioDialog
     */
    public GerarRelatorioDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPeriodo = new javax.swing.JPanel();
        labelGerarRelatorio = new javax.swing.JLabel();
        labelDataInicial = new javax.swing.JLabel();
        labelDataFinal = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        botaoGerar = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setResizable(false);
        setTitle("Gerar Relatório");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painelPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        painelPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder("Período"));

        labelGerarRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelGerarRelatorio.setText("Gerar realatório entre as datas:");

        labelDataInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDataInicial.setText("Data Inicial:");

        labelDataFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDataFinal.setText("Data Final:");

        javax.swing.GroupLayout painelPeriodoLayout = new javax.swing.GroupLayout(painelPeriodo);
        painelPeriodo.setLayout(painelPeriodoLayout);
        painelPeriodoLayout.setHorizontalGroup(
            painelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPeriodoLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(labelGerarRelatorio)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(painelPeriodoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelDataInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDataFinal)
                .addGap(181, 181, 181))
        );
        painelPeriodoLayout.setVerticalGroup(
            painelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPeriodoLayout.createSequentialGroup()
                .addComponent(labelGerarRelatorio)
                .addGap(39, 39, 39)
                .addGroup(painelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataInicial)
                    .addComponent(labelDataFinal))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoGerar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoGerar.setText("  Gerar  ");
        botaoGerar.setToolTipText("Gerar Relatório");
        botaoGerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoGerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCancelar))
                    .addComponent(painelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(painelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoGerar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void botaoGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarActionPerformed
        if(dateDataInicial.getDate().toString().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma data inicial para que o relatório possa ser gerado", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(dateDataFinal.getDate().toString().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma data final para que o relatório possa ser gerado", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            Calendar.getInstance().setTime(dateDataInicial.getDate());
            Calendar.getInstance().setTime(dateDataFinal.getDate());
            //Lógica para gerar um relatório
        }
    }//GEN-LAST:event_botaoGerarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerarRelatorioDialog dialog = new GerarRelatorioDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoGerar;
    private javax.swing.JLabel labelDataFinal;
    private javax.swing.JLabel labelDataInicial;
    private javax.swing.JLabel labelGerarRelatorio;
    private javax.swing.JPanel painelPeriodo;
    // End of variables declaration//GEN-END:variables
}
