/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.oltecnologias.hype.gui;

import br.oltecnologias.hype.controller.GerenciadorDePessoas;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        painelDeLogin1 = new javax.swing.JPanel();
        labelUsuario1 = new javax.swing.JLabel();
        campoNomeUsuario1 = new javax.swing.JTextField();
        labelSenha1 = new javax.swing.JLabel();
        campoSenha1 = new javax.swing.JPasswordField();
        botaoEntrar1 = new javax.swing.JButton();
        labelLogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hype!");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));
        painelGeral.setMinimumSize(new java.awt.Dimension(600, 500));
        painelGeral.setPreferredSize(new java.awt.Dimension(1329, 768));

        painelDeLogin1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        painelDeLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelDeLogin1.setName("hype!\n"); // NOI18N

        labelUsuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsuario1.setText("Login:");

        campoNomeUsuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNomeUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeUsuario1ActionPerformed(evt);
            }
        });

        labelSenha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSenha1.setText("Senha:");

        campoSenha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        botaoEntrar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoEntrar1.setText("Entrar");
        botaoEntrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDeLogin1Layout = new javax.swing.GroupLayout(painelDeLogin1);
        painelDeLogin1.setLayout(painelDeLogin1Layout);
        painelDeLogin1Layout.setHorizontalGroup(
            painelDeLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeLogin1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(painelDeLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelUsuario1)
                    .addComponent(labelSenha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDeLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoEntrar1)
                    .addGroup(painelDeLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoSenha1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addComponent(campoNomeUsuario1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        painelDeLogin1Layout.setVerticalGroup(
            painelDeLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeLogin1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(painelDeLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario1))
                .addGap(39, 39, 39)
                .addGroup(painelDeLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha1))
                .addGap(46, 46, 46)
                .addComponent(botaoEntrar1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        labelLogo1.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        labelLogo1.setText("hype!");

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelDeLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(612, 612, 612)
                .addComponent(labelLogo1)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(labelLogo1)
                .addGap(74, 74, 74)
                .addComponent(painelDeLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 1322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeUsuario1ActionPerformed

    private void botaoEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrar1ActionPerformed
        // validar administrador no sistema
        System.exit(0);
    }//GEN-LAST:event_botaoEntrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar1;
    private javax.swing.JTextField campoNomeUsuario1;
    private javax.swing.JPasswordField campoSenha1;
    private javax.swing.JLabel labelLogo1;
    private javax.swing.JLabel labelSenha1;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JPanel painelDeLogin1;
    private javax.swing.JPanel painelGeral;
    // End of variables declaration//GEN-END:variables
}
