/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.oltecnologias.hype.gui;

import br.oltecnologias.hype.controller.GerenciadorDePessoas;
import br.oltecnologias.hype.exception.ClienteInexistenteException;
import br.oltecnologias.hype.exception.UsuarioInexistenteException;
import br.oltecnologias.hype.model.Cliente;
import java.awt.Cursor;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cliente
 */
public class PrincipalFrame extends javax.swing.JFrame {

    private String loginUsuario;

    /**
     * Cria um novo form PrincipalFrame
     */
    public PrincipalFrame(String login) {
        loginUsuario = login;
        initComponents();
        
        labelNomeLogin.setText("Logado com " + login);
        labelLogoEmpresa.setIcon(new ImageIcon("Imagens\\mini-logo-wide.png"));
        botaoSair.setIcon(new ImageIcon("Imagens\\Sair do sistema.png"));
        //labelLogoSistema.setIcon(new ImageIcon("Imagens\\.png"));
    }

    /**
     * Creates new form PrinFrame
     */
    public PrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        painelTopo = new javax.swing.JPanel();
        labelLogoEmpresa = new javax.swing.JLabel();
        labelNomeLogin = new javax.swing.JLabel();
        labelLogoSistema = new javax.swing.JLabel();
        botaoSair = new javax.swing.JLabel();
        abas = new javax.swing.JTabbedPane();
        painelClientes = new javax.swing.JPanel();
        botaoNovoCliente = new javax.swing.JButton();
        botaoPesquisarCliente = new javax.swing.JButton();
        campoPesquisarCliente = new javax.swing.JTextField();
        comboBoxOrdenarCliente = new javax.swing.JComboBox();
        pnRlCliente = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        labelOrdenar = new javax.swing.JLabel();
        painelProdutos = new javax.swing.JPanel();
        botaoNovoProduto = new javax.swing.JButton();
        botaoPesquisarProduto = new javax.swing.JButton();
        campoPesquisarProduto = new javax.swing.JTextField();
        pnRlProduto = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        labelFiltrarProdutos = new javax.swing.JLabel();
        comboBoxOrdenarProdutos = new javax.swing.JComboBox();
        painelFornecedores = new javax.swing.JPanel();
        botaoNovoFornecedor = new javax.swing.JButton();
        botaoPesquisarFornecedor = new javax.swing.JButton();
        campoPesquisarFornecedor = new javax.swing.JTextField();
        pnRlFornecedores = new javax.swing.JScrollPane();
        tabelaFornecedores = new javax.swing.JTable();
        labelFiltrarFornecedores = new javax.swing.JLabel();
        comboBoxOrdenarFornecedores = new javax.swing.JComboBox();
        painelLocacoes = new javax.swing.JPanel();
        botaoNovaLocacao = new javax.swing.JButton();
        botaoPesquisarLocacao = new javax.swing.JButton();
        campoPesquisarLocacao = new javax.swing.JTextField();
        botaoLocacoesAtrasadas = new javax.swing.JButton();
        botaoLocacoesExtraviadas = new javax.swing.JButton();
        pnRlFornecedores1 = new javax.swing.JScrollPane();
        tabelaFornecedores1 = new javax.swing.JTable();
        labelFiltrarFornecedores1 = new javax.swing.JLabel();
        comboBoxOrdenarFornecedores1 = new javax.swing.JComboBox();
        painelVendas = new javax.swing.JPanel();
        botaoNovaVenda = new javax.swing.JButton();
        botaoPesquisarFornecedor1 = new javax.swing.JButton();
        campoPesquisarVenda = new javax.swing.JTextField();
        comboBoxOrdenarCliente1 = new javax.swing.JComboBox();
        pnRlCliente1 = new javax.swing.JScrollPane();
        tabelaClientes1 = new javax.swing.JTable();
        labelOrdenar1 = new javax.swing.JLabel();
        painelCaixaERelatorios = new javax.swing.JPanel();
        botaoGerarRelatorio = new javax.swing.JButton();
        botaoFecharCaixa = new javax.swing.JButton();
        pnRlCaixaERelatorios = new javax.swing.JScrollPane();
        tabelaMovimentacao = new javax.swing.JTable();
        labelFiltrarMovimentacao = new javax.swing.JLabel();
        labelValorCaixa = new javax.swing.JLabel();
        campoValorCaixa = new javax.swing.JTextField();
        comboBoxOrdenarCaixaEMovimentacao = new javax.swing.JComboBox();
        botaoRegistrarDespesa = new javax.swing.JButton();
        painelConfiguracoes = new javax.swing.JPanel();
        botaoSalvarDiretorioBackup = new javax.swing.JButton();
        botaoProcurarDiretorioBackup = new javax.swing.JButton();
        campoDiretorioBackup = new javax.swing.JTextField();
        labelDiretorioBackups = new javax.swing.JLabel();
        botaoSalvarDiretorioContratos = new javax.swing.JButton();
        botaoProcurarDiretorioContratos = new javax.swing.JButton();
        campoDiretorioContratos = new javax.swing.JTextField();
        labelDiretorioContratos = new javax.swing.JLabel();
        painelAdministrador = new javax.swing.JPanel();
        botaoNovoUsuario = new javax.swing.JButton();
        botaoPesquisarUsuario = new javax.swing.JButton();
        campoPesquisarUsuario = new javax.swing.JTextField();
        pnRlUsuario = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        labelOrdenarUsuario = new javax.swing.JLabel();
        comboBoxUsuario = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 730));
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));
        painelGeral.setPreferredSize(new java.awt.Dimension(1366, 730));

        painelTopo.setBackground(new java.awt.Color(255, 255, 255));

        labelLogoEmpresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        botaoSair.setToolTipText("Sair do Sistema");
        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelTopoLayout = new javax.swing.GroupLayout(painelTopo);
        painelTopo.setLayout(painelTopoLayout);
        painelTopoLayout.setHorizontalGroup(
            painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTopoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelLogoEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLogoSistema)
                .addGap(38, 38, 38)
                .addComponent(botaoSair))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNomeLogin)
                .addGap(91, 91, 91))
        );
        painelTopoLayout.setVerticalGroup(
            painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTopoLayout.createSequentialGroup()
                .addGroup(painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLogoSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLogoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTopoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoSair, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        abas.setBackground(new java.awt.Color(255, 255, 255));
        abas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(153, 153, 153)));
        abas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        abas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        painelClientes.setBackground(new java.awt.Color(255, 255, 255));
        painelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        painelClientes.setPreferredSize(new java.awt.Dimension(1311, 735));
        painelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelClientesMouseClicked(evt);
            }
        });

        botaoNovoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoNovoCliente.setText("Novo Cliente");
        botaoNovoCliente.setToolTipText("Criar novo cliente");
        botaoNovoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoClienteActionPerformed(evt);
            }
        });

        botaoPesquisarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoPesquisarCliente.setText("Pesquisar");
        botaoPesquisarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        campoPesquisarCliente.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        campoPesquisarCliente.setForeground(new java.awt.Color(153, 153, 153));
        campoPesquisarCliente.setText("Pesquisar Cliente");
        campoPesquisarCliente.setToolTipText("Informe o nome do cliente");
        campoPesquisarCliente.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        campoPesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPesquisarClienteMouseClicked(evt);
            }
        });
        campoPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPesquisarClienteKeyTyped(evt);
            }
        });

        comboBoxOrdenarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxOrdenarCliente.setMaximumRowCount(3);
        comboBoxOrdenarCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Últimos locatários", "Últimos cadastros" }));
        comboBoxOrdenarCliente.setToolTipText("Selecionar tipo de filtro");
        comboBoxOrdenarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnRlCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tabelaClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        String[] nomesColunas = {"CPF", "Nome do Cliente", "Última Locação", "", "", "",""};
        //Essa lista terá as linhas da tabela
        List<Object[]> listaLinhas = new ArrayList<>();
        //Adicionando valores nas linhas
        for(Cliente cliente: GerenciadorDePessoas.getInstance().getClientes()) {
            listaLinhas.add(new Object[]{cliente.getCpf(), cliente.getNome(), "20/04/2015",
                new JButton("Ver Medidas"), new JButton("Ver Locações"),
                new JButton("Editar"), new JButton("Excluir")});
    }
    //cria um defaultablemodel com as informações acima
    DefaultTableModel modelo = new DefaultTableModel(
        listaLinhas.toArray(new Object[listaLinhas.size()][]), nomesColunas);
    //define o model da tabela
    tabelaClientes.setModel(modelo);
    pnRlCliente.setViewportView(tabelaClientes);

    labelOrdenar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelOrdenar.setText("Filtrar por:");

    javax.swing.GroupLayout painelClientesLayout = new javax.swing.GroupLayout(painelClientes);
    painelClientes.setLayout(painelClientesLayout);
    painelClientesLayout.setHorizontalGroup(
        painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelClientesLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoNovoCliente)
                .addGroup(painelClientesLayout.createSequentialGroup()
                    .addComponent(campoPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoPesquisarCliente))
                .addGroup(painelClientesLayout.createSequentialGroup()
                    .addComponent(labelOrdenar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboBoxOrdenarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pnRlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(31, Short.MAX_VALUE))
    );
    painelClientesLayout.setVerticalGroup(
        painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelClientesLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(botaoNovoCliente)
            .addGap(50, 50, 50)
            .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoPesquisarCliente))
            .addGap(40, 40, 40)
            .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelOrdenar)
                .addComponent(comboBoxOrdenarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(pnRlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    abas.addTab("  Clientes  ", painelClientes);

    painelProdutos.setBackground(new java.awt.Color(255, 255, 255));
    painelProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    painelProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            painelProdutosMouseClicked(evt);
        }
    });

    botaoNovoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoNovoProduto.setText("Novo Produto");
    botaoNovoProduto.setToolTipText("Criar novo produto");
    botaoNovoProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoNovoProduto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoNovoProdutoActionPerformed(evt);
        }
    });

    botaoPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoPesquisarProduto.setText("Pesquisar");
    botaoPesquisarProduto.setToolTipText("Pesquisar produtos em estoque");
    botaoPesquisarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    campoPesquisarProduto.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    campoPesquisarProduto.setForeground(new java.awt.Color(153, 153, 153));
    campoPesquisarProduto.setText("Pesquisar Produto");
    campoPesquisarProduto.setToolTipText("Informe o nome do produto");
    campoPesquisarProduto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
    campoPesquisarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            campoPesquisarProdutoMouseClicked(evt);
        }
    });
    campoPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            campoPesquisarProdutoKeyTyped(evt);
        }
    });

    pnRlProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    tabelaProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Código", "Descrição do Produto", "Qtd. em estoque", "", "", ""
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    pnRlProduto.setViewportView(tabelaProdutos);

    labelFiltrarProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelFiltrarProdutos.setText("Filtrar por:");

    comboBoxOrdenarProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    comboBoxOrdenarProdutos.setMaximumRowCount(5);
    comboBoxOrdenarProdutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Em estoque", "Produtos de locação", "Produtos de venda", "Últimos locados", "Últimos cadastros" }));
    comboBoxOrdenarProdutos.setToolTipText("Selecionar tipo de filtro");
    comboBoxOrdenarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout painelProdutosLayout = new javax.swing.GroupLayout(painelProdutos);
    painelProdutos.setLayout(painelProdutosLayout);
    painelProdutosLayout.setHorizontalGroup(
        painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelProdutosLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoNovoProduto)
                .addGroup(painelProdutosLayout.createSequentialGroup()
                    .addComponent(campoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoPesquisarProduto))
                .addComponent(pnRlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelProdutosLayout.createSequentialGroup()
                    .addComponent(labelFiltrarProdutos)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboBoxOrdenarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(31, Short.MAX_VALUE))
    );
    painelProdutosLayout.setVerticalGroup(
        painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelProdutosLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(botaoNovoProduto)
            .addGap(50, 50, 50)
            .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoPesquisarProduto))
            .addGap(40, 40, 40)
            .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelFiltrarProdutos)
                .addComponent(comboBoxOrdenarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(pnRlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(73, Short.MAX_VALUE))
    );

    abas.addTab("  Produtos  ", painelProdutos);

    painelFornecedores.setBackground(new java.awt.Color(255, 255, 255));
    painelFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    painelFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            painelFornecedoresMouseClicked(evt);
        }
    });

    botaoNovoFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoNovoFornecedor.setText("Novo Fornecedor");
    botaoNovoFornecedor.setToolTipText("Criar novo fornecedor");
    botaoNovoFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoNovoFornecedorActionPerformed(evt);
        }
    });

    botaoPesquisarFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoPesquisarFornecedor.setText("Pesquisar");
    botaoPesquisarFornecedor.setToolTipText("Pesquisar fornecedores cadastrados");
    botaoPesquisarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    campoPesquisarFornecedor.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    campoPesquisarFornecedor.setForeground(new java.awt.Color(153, 153, 153));
    campoPesquisarFornecedor.setText("Pesquisar Fornecedor");
    campoPesquisarFornecedor.setToolTipText("Informe o nome do fornecedor");
    campoPesquisarFornecedor.setDisabledTextColor(new java.awt.Color(204, 204, 204));
    campoPesquisarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            campoPesquisarFornecedorMouseClicked(evt);
        }
    });
    campoPesquisarFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            campoPesquisarFornecedorKeyTyped(evt);
        }
    });

    pnRlFornecedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    tabelaFornecedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tabelaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Forncedor", "Endereço", "Contato", "", ""
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    pnRlFornecedores.setViewportView(tabelaFornecedores);

    labelFiltrarFornecedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelFiltrarFornecedores.setText("Filtrar por:");

    comboBoxOrdenarFornecedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    comboBoxOrdenarFornecedores.setMaximumRowCount(3);
    comboBoxOrdenarFornecedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Últimos locatários", "Últimos cadastros" }));
    comboBoxOrdenarFornecedores.setToolTipText("Selecionar tipo de filtro");
    comboBoxOrdenarFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout painelFornecedoresLayout = new javax.swing.GroupLayout(painelFornecedores);
    painelFornecedores.setLayout(painelFornecedoresLayout);
    painelFornecedoresLayout.setHorizontalGroup(
        painelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelFornecedoresLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoNovoFornecedor)
                .addGroup(painelFornecedoresLayout.createSequentialGroup()
                    .addComponent(campoPesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoPesquisarFornecedor))
                .addGroup(painelFornecedoresLayout.createSequentialGroup()
                    .addComponent(labelFiltrarFornecedores)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboBoxOrdenarFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pnRlFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(31, Short.MAX_VALUE))
    );
    painelFornecedoresLayout.setVerticalGroup(
        painelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelFornecedoresLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(botaoNovoFornecedor)
            .addGap(50, 50, 50)
            .addGroup(painelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoPesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoPesquisarFornecedor))
            .addGap(40, 40, 40)
            .addGroup(painelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelFiltrarFornecedores)
                .addComponent(comboBoxOrdenarFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(pnRlFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(73, 73, 73))
    );

    abas.addTab("Fornecedores", painelFornecedores);

    painelLocacoes.setBackground(new java.awt.Color(255, 255, 255));
    painelLocacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    painelLocacoes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            painelLocacoesMouseClicked(evt);
        }
    });

    botaoNovaLocacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoNovaLocacao.setText("Nova Locação");
    botaoNovaLocacao.setToolTipText("Criar nova locação");
    botaoNovaLocacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoNovaLocacao.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoNovaLocacaoActionPerformed(evt);
        }
    });

    botaoPesquisarLocacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoPesquisarLocacao.setText("Pesquisar");
    botaoPesquisarLocacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    campoPesquisarLocacao.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    campoPesquisarLocacao.setForeground(new java.awt.Color(153, 153, 153));
    campoPesquisarLocacao.setText("Pesquisar Locação");
    campoPesquisarLocacao.setToolTipText("");
    campoPesquisarLocacao.setDisabledTextColor(new java.awt.Color(204, 204, 204));
    campoPesquisarLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            campoPesquisarLocacaoMouseClicked(evt);
        }
    });
    campoPesquisarLocacao.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            campoPesquisarLocacaoKeyTyped(evt);
        }
    });

    botaoLocacoesAtrasadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoLocacoesAtrasadas.setText("Ver locações Atrasadas");
    botaoLocacoesAtrasadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoLocacoesAtrasadas.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoLocacoesAtrasadasActionPerformed(evt);
        }
    });

    botaoLocacoesExtraviadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoLocacoesExtraviadas.setText("Ver locações Extraviadas");
    botaoLocacoesExtraviadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoLocacoesExtraviadas.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoLocacoesExtraviadasActionPerformed(evt);
        }
    });

    pnRlFornecedores1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    tabelaFornecedores1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tabelaFornecedores1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Cliente", "Produtos Locados", "Contato", "Retorno", ""
        }
    ));
    pnRlFornecedores1.setViewportView(tabelaFornecedores1);

    labelFiltrarFornecedores1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelFiltrarFornecedores1.setText("Filtrar por:");

    comboBoxOrdenarFornecedores1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    comboBoxOrdenarFornecedores1.setMaximumRowCount(3);
    comboBoxOrdenarFornecedores1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Últimas Locações", "Mais Antigas" }));
    comboBoxOrdenarFornecedores1.setToolTipText("Selecionar tipo de filtro");
    comboBoxOrdenarFornecedores1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout painelLocacoesLayout = new javax.swing.GroupLayout(painelLocacoes);
    painelLocacoes.setLayout(painelLocacoesLayout);
    painelLocacoesLayout.setHorizontalGroup(
        painelLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelLocacoesLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLocacoesLayout.createSequentialGroup()
                    .addComponent(labelFiltrarFornecedores1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboBoxOrdenarFornecedores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pnRlFornecedores1, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelLocacoesLayout.createSequentialGroup()
                    .addComponent(botaoNovaLocacao)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoLocacoesAtrasadas)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoLocacoesExtraviadas))
                .addGroup(painelLocacoesLayout.createSequentialGroup()
                    .addComponent(campoPesquisarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoPesquisarLocacao)))
            .addContainerGap(31, Short.MAX_VALUE))
    );
    painelLocacoesLayout.setVerticalGroup(
        painelLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelLocacoesLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(painelLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botaoNovaLocacao)
                .addComponent(botaoLocacoesAtrasadas)
                .addComponent(botaoLocacoesExtraviadas))
            .addGap(50, 50, 50)
            .addGroup(painelLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoPesquisarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoPesquisarLocacao))
            .addGap(40, 40, 40)
            .addGroup(painelLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelFiltrarFornecedores1)
                .addComponent(comboBoxOrdenarFornecedores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(pnRlFornecedores1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(73, Short.MAX_VALUE))
    );

    abas.addTab("  Locações  ", painelLocacoes);

    painelVendas.setBackground(new java.awt.Color(255, 255, 255));
    painelVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    painelVendas.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            painelVendasMouseClicked(evt);
        }
    });

    botaoNovaVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoNovaVenda.setText("Nova Venda");
    botaoNovaVenda.setToolTipText("Criar nova locação");
    botaoNovaVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoNovaVenda.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoNovaVendaActionPerformed(evt);
        }
    });

    botaoPesquisarFornecedor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoPesquisarFornecedor1.setText("Pesquisar");
    botaoPesquisarFornecedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    campoPesquisarVenda.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    campoPesquisarVenda.setForeground(new java.awt.Color(153, 153, 153));
    campoPesquisarVenda.setText("Pesquisar Venda");
    campoPesquisarVenda.setDisabledTextColor(new java.awt.Color(204, 204, 204));
    campoPesquisarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            campoPesquisarVendaMouseClicked(evt);
        }
    });
    campoPesquisarVenda.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            campoPesquisarVendaKeyTyped(evt);
        }
    });

    comboBoxOrdenarCliente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    comboBoxOrdenarCliente1.setMaximumRowCount(3);
    comboBoxOrdenarCliente1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Últimas vendas", "Valor" }));
    comboBoxOrdenarCliente1.setToolTipText("Selecionar tipo de filtro");
    comboBoxOrdenarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    pnRlCliente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    tabelaClientes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tabelaClientes1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Data da venda", "Vendedor", "Valor da venda", "Itens", "Forma pagamento", ""
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    pnRlCliente1.setViewportView(tabelaClientes1);

    labelOrdenar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelOrdenar1.setText("Filtrar por:");

    javax.swing.GroupLayout painelVendasLayout = new javax.swing.GroupLayout(painelVendas);
    painelVendas.setLayout(painelVendasLayout);
    painelVendasLayout.setHorizontalGroup(
        painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelVendasLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelVendasLayout.createSequentialGroup()
                    .addComponent(labelOrdenar1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboBoxOrdenarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pnRlCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoNovaVenda)
                .addGroup(painelVendasLayout.createSequentialGroup()
                    .addComponent(campoPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoPesquisarFornecedor1)))
            .addContainerGap(31, Short.MAX_VALUE))
    );
    painelVendasLayout.setVerticalGroup(
        painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelVendasLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(botaoNovaVenda)
            .addGap(50, 50, 50)
            .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoPesquisarFornecedor1))
            .addGap(40, 40, 40)
            .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelOrdenar1)
                .addComponent(comboBoxOrdenarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(pnRlCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(73, 73, 73))
    );

    abas.addTab("   Vendas   ", painelVendas);

    painelCaixaERelatorios.setBackground(new java.awt.Color(255, 255, 255));
    painelCaixaERelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    botaoGerarRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoGerarRelatorio.setText("Gerar Relatório");
    botaoGerarRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoGerarRelatorioActionPerformed(evt);
        }
    });

    botaoFecharCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoFecharCaixa.setText("Fechar Caixa");
    botaoFecharCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    tabelaMovimentacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tabelaMovimentacao.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Movimento", "Valor", "Data", "Responsável", "Motivo"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    pnRlCaixaERelatorios.setViewportView(tabelaMovimentacao);

    labelFiltrarMovimentacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelFiltrarMovimentacao.setText("Filtrar por:");

    labelValorCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    labelValorCaixa.setText("Valor em Caixa:");

    campoValorCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    comboBoxOrdenarCaixaEMovimentacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    comboBoxOrdenarCaixaEMovimentacao.setMaximumRowCount(3);
    comboBoxOrdenarCaixaEMovimentacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordem alfabética", "Últimos locatários", "Últimos cadastrados", "Pendências", "Despesas" }));
    comboBoxOrdenarCaixaEMovimentacao.setToolTipText("Selecionar tipo de filtro");
    comboBoxOrdenarCaixaEMovimentacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    botaoRegistrarDespesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoRegistrarDespesa.setText("Registrar Despesa");
    botaoRegistrarDespesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoRegistrarDespesa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoRegistrarDespesaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout painelCaixaERelatoriosLayout = new javax.swing.GroupLayout(painelCaixaERelatorios);
    painelCaixaERelatorios.setLayout(painelCaixaERelatoriosLayout);
    painelCaixaERelatoriosLayout.setHorizontalGroup(
        painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelCaixaERelatoriosLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelCaixaERelatoriosLayout.createSequentialGroup()
                    .addGroup(painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCaixaERelatoriosLayout.createSequentialGroup()
                            .addComponent(labelFiltrarMovimentacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBoxOrdenarCaixaEMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnRlCaixaERelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(31, Short.MAX_VALUE))
                .addGroup(painelCaixaERelatoriosLayout.createSequentialGroup()
                    .addComponent(botaoGerarRelatorio)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoFecharCaixa)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoRegistrarDespesa)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelValorCaixa)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoValorCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(53, 53, 53))))
    );
    painelCaixaERelatoriosLayout.setVerticalGroup(
        painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelCaixaERelatoriosLayout.createSequentialGroup()
            .addGroup(painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelCaixaERelatoriosLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoGerarRelatorio)
                        .addComponent(botaoFecharCaixa)
                        .addComponent(botaoRegistrarDespesa)))
                .addGroup(painelCaixaERelatoriosLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelValorCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoValorCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(40, 40, 40)
            .addGroup(painelCaixaERelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelFiltrarMovimentacao)
                .addComponent(comboBoxOrdenarCaixaEMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(pnRlCaixaERelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(127, Short.MAX_VALUE))
    );

    abas.addTab("Relatório e Caixa", painelCaixaERelatorios);

    painelConfiguracoes.setBackground(new java.awt.Color(255, 255, 255));
    painelConfiguracoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    painelConfiguracoes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            painelConfiguracoesMouseClicked(evt);
        }
    });

    botaoSalvarDiretorioBackup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoSalvarDiretorioBackup.setText(" Salvar ");
    botaoSalvarDiretorioBackup.setToolTipText("Salvar diretório");
    botaoSalvarDiretorioBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoSalvarDiretorioBackup.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoSalvarDiretorioBackupActionPerformed(evt);
        }
    });

    botaoProcurarDiretorioBackup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoProcurarDiretorioBackup.setText("Procurar");
    botaoProcurarDiretorioBackup.setToolTipText("Procurar diretório");
    botaoProcurarDiretorioBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    campoDiretorioBackup.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    campoDiretorioBackup.setForeground(new java.awt.Color(153, 153, 153));
    campoDiretorioBackup.setText("Caminho do diretório");
    campoDiretorioBackup.setToolTipText("Informe o caminho do diretório");
    campoDiretorioBackup.setDisabledTextColor(new java.awt.Color(204, 204, 204));
    campoDiretorioBackup.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            campoDiretorioBackupMouseClicked(evt);
        }
    });
    campoDiretorioBackup.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            campoDiretorioBackupKeyTyped(evt);
        }
    });

    labelDiretorioBackups.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelDiretorioBackups.setText("Diretório de backups");

    botaoSalvarDiretorioContratos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoSalvarDiretorioContratos.setText(" Salvar ");
    botaoSalvarDiretorioContratos.setToolTipText("Salvar diretório");
    botaoSalvarDiretorioContratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoSalvarDiretorioContratos.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoSalvarDiretorioContratosActionPerformed(evt);
        }
    });

    botaoProcurarDiretorioContratos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoProcurarDiretorioContratos.setText("Procurar");
    botaoProcurarDiretorioContratos.setToolTipText("Procurar diretório");
    botaoProcurarDiretorioContratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    campoDiretorioContratos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    campoDiretorioContratos.setForeground(new java.awt.Color(153, 153, 153));
    campoDiretorioContratos.setText("Caminho do diretório");
    campoDiretorioContratos.setToolTipText("Informe o caminho do diretório");
    campoDiretorioContratos.setDisabledTextColor(new java.awt.Color(204, 204, 204));
    campoDiretorioContratos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            campoDiretorioContratosMouseClicked(evt);
        }
    });
    campoDiretorioContratos.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            campoDiretorioContratosKeyTyped(evt);
        }
    });

    labelDiretorioContratos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelDiretorioContratos.setText("Diretório de Contratos");

    javax.swing.GroupLayout painelConfiguracoesLayout = new javax.swing.GroupLayout(painelConfiguracoes);
    painelConfiguracoes.setLayout(painelConfiguracoesLayout);
    painelConfiguracoesLayout.setHorizontalGroup(
        painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelConfiguracoesLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelDiretorioContratos)
                .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                    .addComponent(campoDiretorioContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoProcurarDiretorioContratos)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoSalvarDiretorioContratos))
                .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                    .addComponent(campoDiretorioBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoProcurarDiretorioBackup)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoSalvarDiretorioBackup))
                .addComponent(labelDiretorioBackups))
            .addContainerGap(647, Short.MAX_VALUE))
    );
    painelConfiguracoesLayout.setVerticalGroup(
        painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelConfiguracoesLayout.createSequentialGroup()
            .addGap(66, 66, 66)
            .addComponent(labelDiretorioBackups)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoDiretorioBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoProcurarDiretorioBackup)
                .addComponent(botaoSalvarDiretorioBackup))
            .addGap(31, 31, 31)
            .addComponent(labelDiretorioContratos)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoDiretorioContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoProcurarDiretorioContratos)
                .addComponent(botaoSalvarDiretorioContratos))
            .addContainerGap(438, Short.MAX_VALUE))
    );

    abas.addTab("Configuração", painelConfiguracoes);

    painelAdministrador.setBackground(new java.awt.Color(255, 255, 255));
    painelAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    painelAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            painelAdministradorMouseClicked(evt);
        }
    });

    botaoNovoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoNovoUsuario.setText("Novo Usuário");
    botaoNovoUsuario.setToolTipText("Criar novo usuário");
    botaoNovoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botaoNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botaoNovoUsuarioActionPerformed(evt);
        }
    });

    botaoPesquisarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    botaoPesquisarUsuario.setText("Pesquisar");
    botaoPesquisarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    campoPesquisarUsuario.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    campoPesquisarUsuario.setForeground(new java.awt.Color(153, 153, 153));
    campoPesquisarUsuario.setText("Pesquisar Usuário");
    campoPesquisarUsuario.setToolTipText("Informe o nome do usuário");
    campoPesquisarUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
    campoPesquisarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            campoPesquisarUsuarioMouseClicked(evt);
        }
    });
    campoPesquisarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            campoPesquisarUsuarioKeyTyped(evt);
        }
    });

    pnRlUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    tabelaUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Nome", "Login", "Cadastrado desde", "", ""
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    pnRlUsuario.setViewportView(tabelaUsuario);

    labelOrdenarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelOrdenarUsuario.setText("Filtrar por:");

    comboBoxUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    comboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Últimos cadastros" }));
    comboBoxUsuario.setToolTipText("Selecionar tipo de filtro");
    comboBoxUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jButton1.setText("Gerar Recibo");
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout painelAdministradorLayout = new javax.swing.GroupLayout(painelAdministrador);
    painelAdministrador.setLayout(painelAdministradorLayout);
    painelAdministradorLayout.setHorizontalGroup(
        painelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelAdministradorLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(painelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelAdministradorLayout.createSequentialGroup()
                    .addComponent(botaoNovoUsuario)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1))
                .addGroup(painelAdministradorLayout.createSequentialGroup()
                    .addComponent(campoPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(botaoPesquisarUsuario))
                .addComponent(pnRlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelAdministradorLayout.createSequentialGroup()
                    .addComponent(labelOrdenarUsuario)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(31, Short.MAX_VALUE))
    );
    painelAdministradorLayout.setVerticalGroup(
        painelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelAdministradorLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(painelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botaoNovoUsuario)
                .addComponent(jButton1))
            .addGap(49, 49, 49)
            .addGroup(painelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoPesquisarUsuario))
            .addGap(40, 40, 40)
            .addGroup(painelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelOrdenarUsuario)
                .addComponent(comboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(pnRlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(74, Short.MAX_VALUE))
    );

    try {
        if(GerenciadorDePessoas.getInstance().isAdministrador(loginUsuario)) {

            abas.addTab("Administrador", painelAdministrador);
        }
    } catch (UsuarioInexistenteException e) {
        setVisible(false);
        new LoginFrame().setVisible(true);
    }

    javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
    painelGeral.setLayout(painelGeralLayout);
    painelGeralLayout.setHorizontalGroup(
        painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelGeralLayout.createSequentialGroup()
            .addContainerGap(19, Short.MAX_VALUE)
            .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(abas)
                .addComponent(painelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(19, Short.MAX_VALUE))
    );
    painelGeralLayout.setVerticalGroup(
        painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelGeralLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(painelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(abas, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(painelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(painelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 1, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoClienteActionPerformed
        //Dialog dialog = new CadastrarClienteDialog(this, true);
        //dialog.setLocationRelativeTo(null);
        //dialog.setVisible(true);
        
        CadastrarClienteDialog dialog = new CadastrarClienteDialog(null);
        dialog.setLocationRelativeTo(null);
        if (dialog.alterarDados()) {
            
            //lógica para atualizar a tabela... refazer apenas atualizando o modelo
            String[] nomesColunas = {"CPF", "Nome do Cliente", "Última Locação", "", "", "", ""};
            //Essa lista terá as linhas da tabela
            List<Object[]> listaLinhas = new ArrayList<>();
            
            JButton botaoMedidas = new JButton("Ver Medidas");
            JButton botaoLocacoes = new JButton("Ver Locações");
            JButton botaoEditar = new JButton("Editar");
            JButton botaoExcluir = new JButton("Excluir");
            
            botaoMedidas.setCursor(new Cursor(Cursor.HAND_CURSOR));
            botaoLocacoes.setCursor(new Cursor(Cursor.HAND_CURSOR));
            botaoEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
            botaoExcluir.setCursor(new Cursor(Cursor.HAND_CURSOR));
            
            //Adicionando valores nas linhas
            for (Cliente cliente : GerenciadorDePessoas.getInstance().getClientes()) {
                listaLinhas.add(new Object[]{cliente.getCpf(), cliente.getNome(), "20/04/2015",
                    "", "",
                    "", ""});
            }
            //cria um defaultablemodel com as informações acima
            DefaultTableModel modelo = new DefaultTableModel(
                    listaLinhas.toArray(new Object[listaLinhas.size()][]), nomesColunas);
            //define o model da tabela
            tabelaClientes.setModel(modelo);
            
        }
        dialog.dispose();
    }//GEN-LAST:event_botaoNovoClienteActionPerformed

    private void campoPesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarClienteMouseClicked
        if(campoPesquisarCliente.getText().equals("Pesquisar Cliente")) {
            eliminarTextoDeCampo(campoPesquisarCliente);
        }
    }//GEN-LAST:event_campoPesquisarClienteMouseClicked

    private void campoPesquisarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarClienteKeyTyped
        if(campoPesquisarCliente.getText().equals("Pesquisar Cliente")) {
            eliminarTextoDeCampo(campoPesquisarCliente);
        }
    }//GEN-LAST:event_campoPesquisarClienteKeyTyped

    private void painelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelClientesMouseClicked
        if(campoPesquisarCliente.getText().length() <= 0) {
            criarTextoEmCampo(campoPesquisarCliente, "Pesquisar Cliente");
        }
    }//GEN-LAST:event_painelClientesMouseClicked

    private void botaoNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoProdutoActionPerformed
        Dialog dialog = new CadastrarProdutoDialog(new java.awt.Frame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_botaoNovoProdutoActionPerformed

    private void campoPesquisarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarProdutoMouseClicked
        if(campoPesquisarProduto.getText().equals("Pesquisar Produto")) {
            eliminarTextoDeCampo(campoPesquisarProduto);
        }
    }//GEN-LAST:event_campoPesquisarProdutoMouseClicked

    private void campoPesquisarProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarProdutoKeyTyped
        if(campoPesquisarProduto.getText().equals("Pesquisar Produto")) {
            eliminarTextoDeCampo(campoPesquisarProduto);
        }
    }//GEN-LAST:event_campoPesquisarProdutoKeyTyped

    private void painelProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelProdutosMouseClicked
        if(campoPesquisarProduto.getText().length() <= 0) {
            criarTextoEmCampo(campoPesquisarProduto, "Pesquisar Produto");
        }
    }//GEN-LAST:event_painelProdutosMouseClicked

    private void botaoNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoFornecedorActionPerformed
        Dialog dialog = new CadastrarFornecedorDialog(new java.awt.Frame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_botaoNovoFornecedorActionPerformed

    private void campoPesquisarFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarFornecedorMouseClicked
        if(campoPesquisarFornecedor.getText().equals("Pesquisar Fornecedor")) {
            eliminarTextoDeCampo(campoPesquisarFornecedor);
        }
    }//GEN-LAST:event_campoPesquisarFornecedorMouseClicked

    private void campoPesquisarFornecedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarFornecedorKeyTyped
        if(campoPesquisarFornecedor.getText().equals("Pesquisar Fornecedor")) {
            eliminarTextoDeCampo(campoPesquisarFornecedor);
        }
    }//GEN-LAST:event_campoPesquisarFornecedorKeyTyped

    private void painelFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelFornecedoresMouseClicked
        if(campoPesquisarFornecedor.getText().length() <= 0) {
            criarTextoEmCampo(campoPesquisarFornecedor, "Pesquisar Fornecedor");
        }
    }//GEN-LAST:event_painelFornecedoresMouseClicked

    private void botaoNovaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovaLocacaoActionPerformed
        Dialog dialog = new RealizarLocacaoDialog(new java.awt.Frame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_botaoNovaLocacaoActionPerformed

    private void campoPesquisarLocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarLocacaoMouseClicked
        if(campoPesquisarLocacao.getText().equals("Pesquisar Locação")) {
            eliminarTextoDeCampo(campoPesquisarLocacao);
        }
    }//GEN-LAST:event_campoPesquisarLocacaoMouseClicked

    private void campoPesquisarLocacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarLocacaoKeyTyped
        if(campoPesquisarLocacao.getText().equals("Pesquisar Locação")) {
            eliminarTextoDeCampo(campoPesquisarLocacao);
        }
    }//GEN-LAST:event_campoPesquisarLocacaoKeyTyped

    private void botaoLocacoesAtrasadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLocacoesAtrasadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLocacoesAtrasadasActionPerformed

    private void botaoLocacoesExtraviadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLocacoesExtraviadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLocacoesExtraviadasActionPerformed

    private void painelLocacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelLocacoesMouseClicked
        if(campoPesquisarLocacao.getText().length() <= 0) {
            criarTextoEmCampo(campoPesquisarLocacao, "Pesquisar Locação");
        }
    }//GEN-LAST:event_painelLocacoesMouseClicked

    private void botaoNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovaVendaActionPerformed
        Dialog dialog = new RealizarVendaDialog(new java.awt.Frame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_botaoNovaVendaActionPerformed

    private void campoPesquisarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarVendaMouseClicked
        if(campoPesquisarVenda.getText().equals("Pesquisar Venda")) {
            eliminarTextoDeCampo(campoPesquisarVenda);
        }
    }//GEN-LAST:event_campoPesquisarVendaMouseClicked

    private void campoPesquisarVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarVendaKeyTyped
        if(campoPesquisarVenda.getText().equals("Pesquisar Venda")) {
            eliminarTextoDeCampo(campoPesquisarVenda);
        }
    }//GEN-LAST:event_campoPesquisarVendaKeyTyped

    private void painelVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelVendasMouseClicked
        if(campoPesquisarVenda.getText().length() <= 0) {
            criarTextoEmCampo(campoPesquisarVenda, "Pesquisar Venda");
        }
    }//GEN-LAST:event_painelVendasMouseClicked

    private void botaoGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGerarRelatorioActionPerformed

    private void botaoRegistrarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRegistrarDespesaActionPerformed

    private void botaoSalvarDiretorioBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarDiretorioBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvarDiretorioBackupActionPerformed

    private void campoDiretorioBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDiretorioBackupMouseClicked
        if(campoDiretorioBackup.getText().equals("Caminho do diretório")) {
            eliminarTextoDeCampo(campoDiretorioBackup);
        }
    }//GEN-LAST:event_campoDiretorioBackupMouseClicked

    private void campoDiretorioBackupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDiretorioBackupKeyTyped
        if(campoDiretorioBackup.getText().equals("Caminho do diretório")) {
            eliminarTextoDeCampo(campoDiretorioBackup);
        }
    }//GEN-LAST:event_campoDiretorioBackupKeyTyped

    private void botaoSalvarDiretorioContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarDiretorioContratosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvarDiretorioContratosActionPerformed

    private void campoDiretorioContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDiretorioContratosMouseClicked
        if(campoDiretorioContratos.getText().equals("Caminho do diretório")) {
            eliminarTextoDeCampo(campoDiretorioContratos);
        }
    }//GEN-LAST:event_campoDiretorioContratosMouseClicked

    private void campoDiretorioContratosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDiretorioContratosKeyTyped
        if(campoDiretorioContratos.getText().equals("Caminho do diretório")) {
            eliminarTextoDeCampo(campoDiretorioContratos);
        }
    }//GEN-LAST:event_campoDiretorioContratosKeyTyped

    private void painelConfiguracoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelConfiguracoesMouseClicked
        if(campoDiretorioBackup.getText().length() <= 0) {
            criarTextoEmCampo(campoDiretorioBackup, "Caminho do diretório");
        }
        if(campoDiretorioContratos.getText().length() <= 0) {
            criarTextoEmCampo(campoDiretorioContratos, "Caminho do diretório");
        }
    }//GEN-LAST:event_painelConfiguracoesMouseClicked

    private void botaoNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoUsuarioActionPerformed
        Dialog dialog = new CadastrarUsuarioDialog(new java.awt.Frame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_botaoNovoUsuarioActionPerformed

    private void campoPesquisarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarUsuarioMouseClicked
        if(campoPesquisarUsuario.getText().equals("Pesquisar Usuário")) {
            eliminarTextoDeCampo(campoPesquisarUsuario);
        }
    }//GEN-LAST:event_campoPesquisarUsuarioMouseClicked

    private void campoPesquisarUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarUsuarioKeyTyped
        if(campoPesquisarUsuario.getText().equals("Pesquisar Usuário")) {
            eliminarTextoDeCampo(campoPesquisarUsuario);
        }
    }//GEN-LAST:event_campoPesquisarUsuarioKeyTyped

    private void painelAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelAdministradorMouseClicked
        if(campoPesquisarUsuario.getText().length() <= 0) {
            criarTextoEmCampo(campoPesquisarUsuario, "Pesquisar Usuário");
        }
    }//GEN-LAST:event_painelAdministradorMouseClicked

    private void botaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseClicked
        setVisible(false);
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_botaoSairMouseClicked
    
    public void eliminarTextoDeCampo(javax.swing.JTextField campo) {
        campo.setText("");
        campo.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        campo.setForeground(new java.awt.Color(0, 0, 0));
    }
    
    public void criarTextoEmCampo(javax.swing.JTextField campo, String mensagem) {
        campo.setText(mensagem);
        campo.setForeground(new java.awt.Color(153, 153, 153));
        campo.setFont(new java.awt.Font("Tahoma", 2, 14));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton botaoFecharCaixa;
    private javax.swing.JButton botaoGerarRelatorio;
    private javax.swing.JButton botaoLocacoesAtrasadas;
    private javax.swing.JButton botaoLocacoesExtraviadas;
    private javax.swing.JButton botaoNovaLocacao;
    private javax.swing.JButton botaoNovaVenda;
    private javax.swing.JButton botaoNovoCliente;
    private javax.swing.JButton botaoNovoFornecedor;
    private javax.swing.JButton botaoNovoProduto;
    private javax.swing.JButton botaoNovoUsuario;
    private javax.swing.JButton botaoPesquisarCliente;
    private javax.swing.JButton botaoPesquisarFornecedor;
    private javax.swing.JButton botaoPesquisarFornecedor1;
    private javax.swing.JButton botaoPesquisarLocacao;
    private javax.swing.JButton botaoPesquisarProduto;
    private javax.swing.JButton botaoPesquisarUsuario;
    private javax.swing.JButton botaoProcurarDiretorioBackup;
    private javax.swing.JButton botaoProcurarDiretorioContratos;
    private javax.swing.JButton botaoRegistrarDespesa;
    private javax.swing.JLabel botaoSair;
    private javax.swing.JButton botaoSalvarDiretorioBackup;
    private javax.swing.JButton botaoSalvarDiretorioContratos;
    private javax.swing.JTextField campoDiretorioBackup;
    private javax.swing.JTextField campoDiretorioContratos;
    private javax.swing.JTextField campoPesquisarCliente;
    private javax.swing.JTextField campoPesquisarFornecedor;
    private javax.swing.JTextField campoPesquisarLocacao;
    private javax.swing.JTextField campoPesquisarProduto;
    private javax.swing.JTextField campoPesquisarUsuario;
    private javax.swing.JTextField campoPesquisarVenda;
    private javax.swing.JTextField campoValorCaixa;
    private javax.swing.JComboBox comboBoxOrdenarCaixaEMovimentacao;
    private javax.swing.JComboBox comboBoxOrdenarCliente;
    private javax.swing.JComboBox comboBoxOrdenarCliente1;
    private javax.swing.JComboBox comboBoxOrdenarFornecedores;
    private javax.swing.JComboBox comboBoxOrdenarFornecedores1;
    private javax.swing.JComboBox comboBoxOrdenarProdutos;
    private javax.swing.JComboBox comboBoxUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelDiretorioBackups;
    private javax.swing.JLabel labelDiretorioContratos;
    private javax.swing.JLabel labelFiltrarFornecedores;
    private javax.swing.JLabel labelFiltrarFornecedores1;
    private javax.swing.JLabel labelFiltrarMovimentacao;
    private javax.swing.JLabel labelFiltrarProdutos;
    private javax.swing.JLabel labelLogoEmpresa;
    private javax.swing.JLabel labelLogoSistema;
    private javax.swing.JLabel labelNomeLogin;
    private javax.swing.JLabel labelOrdenar;
    private javax.swing.JLabel labelOrdenar1;
    private javax.swing.JLabel labelOrdenarUsuario;
    private javax.swing.JLabel labelValorCaixa;
    private javax.swing.JPanel painelAdministrador;
    private javax.swing.JPanel painelCaixaERelatorios;
    private javax.swing.JPanel painelClientes;
    private javax.swing.JPanel painelConfiguracoes;
    private javax.swing.JPanel painelFornecedores;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelLocacoes;
    private javax.swing.JPanel painelProdutos;
    private javax.swing.JPanel painelTopo;
    private javax.swing.JPanel painelVendas;
    private javax.swing.JScrollPane pnRlCaixaERelatorios;
    private javax.swing.JScrollPane pnRlCliente;
    private javax.swing.JScrollPane pnRlCliente1;
    private javax.swing.JScrollPane pnRlFornecedores;
    private javax.swing.JScrollPane pnRlFornecedores1;
    private javax.swing.JScrollPane pnRlProduto;
    private javax.swing.JScrollPane pnRlUsuario;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaClientes1;
    private javax.swing.JTable tabelaFornecedores;
    private javax.swing.JTable tabelaFornecedores1;
    private javax.swing.JTable tabelaMovimentacao;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTable tabelaUsuario;
    // End of variables declaration//GEN-END:variables
}
